#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v26
# autospec commit: 99a7985
#
# Source0 file verified with key 0x7F3CEA63AE251B69 (mail@nlohmann.me)
#
Name     : nlohmann_json
Version  : 3.12.0
Release  : 2
URL      : https://github.com/nlohmann/json/releases/download/v3.12.0/json.tar.xz
Source0  : https://github.com/nlohmann/json/releases/download/v3.12.0/json.tar.xz
Source1  : https://github.com/nlohmann/json/releases/download/v3.12.0/json.tar.xz.asc
Source2  : 7F3CEA63AE251B69.pkey
Summary  : JSON for Modern C++
Group    : Development/Tools
License  : MIT
Requires: nlohmann_json-data = %{version}-%{release}
Requires: nlohmann_json-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : gnupg
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the nlohmann_json package.
Group: Data

%description data
data components for the nlohmann_json package.


%package dev
Summary: dev components for the nlohmann_json package.
Group: Development
Requires: nlohmann_json-data = %{version}-%{release}
Provides: nlohmann_json-devel = %{version}-%{release}
Requires: nlohmann_json = %{version}-%{release}

%description dev
dev components for the nlohmann_json package.


%package license
Summary: license components for the nlohmann_json package.
Group: Default

%description license
license components for the nlohmann_json package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 7F3CEA63AE251B69' gpg.status
%setup -q -n json
cd %{_builddir}/json

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747680825
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DJSON_BuildTests=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1747680825
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nlohmann_json
cp %{_builddir}/json/LICENSE.MIT %{buildroot}/usr/share/package-licenses/nlohmann_json/8dfc756770a15a88a19e9dbc62529dd11258be8b || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/nlohmann/adl_serializer.hpp
/usr/include/nlohmann/byte_container_with_subtype.hpp
/usr/include/nlohmann/detail/abi_macros.hpp
/usr/include/nlohmann/detail/conversions/from_json.hpp
/usr/include/nlohmann/detail/conversions/to_chars.hpp
/usr/include/nlohmann/detail/conversions/to_json.hpp
/usr/include/nlohmann/detail/exceptions.hpp
/usr/include/nlohmann/detail/hash.hpp
/usr/include/nlohmann/detail/input/binary_reader.hpp
/usr/include/nlohmann/detail/input/input_adapters.hpp
/usr/include/nlohmann/detail/input/json_sax.hpp
/usr/include/nlohmann/detail/input/lexer.hpp
/usr/include/nlohmann/detail/input/parser.hpp
/usr/include/nlohmann/detail/input/position_t.hpp
/usr/include/nlohmann/detail/iterators/internal_iterator.hpp
/usr/include/nlohmann/detail/iterators/iter_impl.hpp
/usr/include/nlohmann/detail/iterators/iteration_proxy.hpp
/usr/include/nlohmann/detail/iterators/iterator_traits.hpp
/usr/include/nlohmann/detail/iterators/json_reverse_iterator.hpp
/usr/include/nlohmann/detail/iterators/primitive_iterator.hpp
/usr/include/nlohmann/detail/json_custom_base_class.hpp
/usr/include/nlohmann/detail/json_pointer.hpp
/usr/include/nlohmann/detail/json_ref.hpp
/usr/include/nlohmann/detail/macro_scope.hpp
/usr/include/nlohmann/detail/macro_unscope.hpp
/usr/include/nlohmann/detail/meta/call_std/begin.hpp
/usr/include/nlohmann/detail/meta/call_std/end.hpp
/usr/include/nlohmann/detail/meta/cpp_future.hpp
/usr/include/nlohmann/detail/meta/detected.hpp
/usr/include/nlohmann/detail/meta/identity_tag.hpp
/usr/include/nlohmann/detail/meta/is_sax.hpp
/usr/include/nlohmann/detail/meta/std_fs.hpp
/usr/include/nlohmann/detail/meta/type_traits.hpp
/usr/include/nlohmann/detail/meta/void_t.hpp
/usr/include/nlohmann/detail/output/binary_writer.hpp
/usr/include/nlohmann/detail/output/output_adapters.hpp
/usr/include/nlohmann/detail/output/serializer.hpp
/usr/include/nlohmann/detail/string_concat.hpp
/usr/include/nlohmann/detail/string_escape.hpp
/usr/include/nlohmann/detail/string_utils.hpp
/usr/include/nlohmann/detail/value_t.hpp
/usr/include/nlohmann/json.hpp
/usr/include/nlohmann/json_fwd.hpp
/usr/include/nlohmann/ordered_map.hpp
/usr/include/nlohmann/thirdparty/hedley/hedley.hpp
/usr/include/nlohmann/thirdparty/hedley/hedley_undef.hpp
/usr/lib64/pkgconfig/nlohmann_json.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nlohmann_json/8dfc756770a15a88a19e9dbc62529dd11258be8b
